# File: k8s/p1_api_service.yaml
apiVersion: v1
kind: Service
metadata:
  name: p1-fraud-api-service
spec:
  selector:
    app: p1-fraud-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
  