# File: k8s/p1_api_deployment.yaml (Final Version)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: p1-fraud-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p1-fraud-api
  template:
    metadata:
      labels:
        app: p1-fraud-api
    spec:
      containers:
      - name: p1-fraud-api-container
        image: p1-fraud-api:v5
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        ports:
        - containerPort: 8000
        
        # --- Health Probes to ensure stability ---
        readinessProbe:
          httpGet:
            path: / # Use the root endpoint "/" as the health check
            port: 8000
          initialDelaySeconds: 15 # Wait 15s after container starts before first check
          periodSeconds: 10     # Check every 10 seconds
          timeoutSeconds: 5       # Consider the check failed if no response in 5s
          failureThreshold: 3     # Restart the container after 3 failed checks
        
        livenessProbe:
          httpGet:
            path: / # Use the same root endpoint
            port: 8000
          initialDelaySeconds: 30 # Wait longer before checking if it's "alive"
          periodSeconds: 20     # Check less frequently once running
          timeoutSeconds: 5
          failureThreshold: 3